spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

inventory_url: "http://localhost:8082/api/inventory/"
inventory_service_name: "inventory"