services:
  mysql:
    image: mysql
    container_name: product_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: products
    volumes:
      - ./data:/var/lib/mysql
